### ISSUE TITLE
conda-forge package?

### ISSUE THREAD

**Issue by Zeitsperre** [KipCrossing/geotiff#35]
Hi there,

I'm currently drafting a conda-forge (https://conda-forge.org/) package that now uses this library and was hoping to include it in its requirements, but there is no conda-forge package for `geotiff`. I'm wondering if you would be interested in having this available on conda-forge?

The packaging and maintenance are very easy, and I can open a PR and contribute a recipe if you'd like. Upkeep/versioning is fully automated with little intervention needed. Given that the name `geotiff` is presently taken by the `libgeotiff` maintainers, all that this package would need is a different name (`geotiff-python`? `python-geotiff`?).

Please let me know if this would be of interest to you and thanks for contributing to the noGDAL ecosystem!

**Comment by KipCrossing** [comment]
@Zeitsperre Hey! Sounds good. Although I personally don't use conda, a PR would be appreciated. 

hmm, that's annoying that `geotiff` has already been taken. How about `pygeotiff`? if not, the ones you suggested are fine. 

> noGDAL ecosystem

^ love this

**Comment by cehbrecht** [comment]
@KipCrossing @Zeitsperre I think we should name the conda package `python-geotiff`. Example on conda-forge:
https://github.com/conda-forge/python-graphviz-feedstock

You can add me also as maintainer.

**Comment by KipCrossing** [comment]
@Zeitsperre Would you like to make a PR with instructions for conda installation in the README

**Comment by Zeitsperre** [comment]
Sure thing, I can write something up very quick today or tomorrow!

**Comment by Zeitsperre** [comment]
Conda-forge package is now available!

**Comment by KipCrossing** [comment]
@Zeitsperre Great work! thanks
