### ISSUE TITLE
Bundle LICENSE file in package

### ISSUE THREAD

**Issue by Zeitsperre** [KipCrossing/geotiff#36]
Bundling the LICENSE file with the source and wheel distributions of the package is a base requirement for building and publishing a package on `conda-forge`. As it stands, this file only exists in the repo and not the package (IE: PyPI).

The good news is that fixing this is pretty simple: https://stackoverflow.com/questions/9977889/how-to-include-license-file-in-setup-py-script

Approach 1: Add the LICENSE file to a `setup.cfg`
Approach 2: Add the LICENSE file to a `MANIFEST.in`
Approach 3: Add a metadata field to the `setup.py` (`license_files`) that points to the LICENSE file (I've never done this, but looks simple enough).
(The overengineered) Approach 4: Completely redesign the installation process by using `pyproject.toml` and `poetry`

Any one of these approaches should work. Personally, I find having both 1 and 2 are nice to have (`setup.cfg` can specify other tooling configurations and `MANIFEST.in` is a guarantee that a bad `setup.cfg` doesn't remove necessary files from the package.)

Let me know if you have a preference and I can submit a PR if you'd like.

**Comment by KipCrossing** [comment]
@Zeitsperre Have a look at #37 

If it looks all g, I'll merge
