### ISSUE TITLE
Use a development recipe and open requirements pins

### ISSUE THREAD

**Issue by Zeitsperre** [KipCrossing/geotiff#41]
The `requirements.txt` currently lists `pytest` as an installation dependency. This means that running an environment test like `$ pip check` will raise an issue in a clean installation if pytest is not installed. Since this should only be installed in a development running tests, it would be good to move this to its own install recipe.

Additionally, I noticed that both `tifffile` and `zarr` are pinned to specific versions. This causes issues in Anaconda, as this dependency limitation can severely restrict the dependency solver. Would it be preferable to set a lower limit on this pin?

I can help with setting this up if you'd like!

**Comment by KipCrossing** [comment]
@Zeitsperre Thanks for picking these up. Please make a PR with the changes and bump the version number in it. Thanks!

**Comment by KipCrossing** [comment]
I've added you as a collaborator [click here](https://github.com/KipCrossing/geotiff/invitations) so you can make branches, etc.
